{
 "title": "VoltDB",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "VoltDB Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_up" }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_cluster_ready" }
   ]
  },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "voltdb_cpu_percent_used", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Server RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "voltdb_server_ram_used", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cluster Latency (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "voltdb_cluster_latency99", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cluster Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "txn/s" }
   ],
   "targets": [
    { "expr": "voltdb_cluster_txns", "legendFormat": "{{job}}" }
   ]
  }
 ]
}