{
 "title": "VoltDB",
 "time": { "from": "2018-08-09T19:50:40.169Z", "to": "2018-08-09T19:52:01.440Z" },
 "panels": [
  {
   "title": "VoltDB Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_up" }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_cluster_ready" }
   ]
  },
  {
   "title": "Database Replication Role",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_dr_role" }
   ]
  },
  {
   "title": "Database Replication State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "voltdb_dr_state" }
   ]
  },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "voltdb_cpu_percent_used", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Server RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "voltdb_server_ram_used/1000000", "legendFormat": "RAM" }
   ]
  },
  {
   "title": "Cluster Latency (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "voltdb_cluster_latency99/1000", "legendFormat": "LATENCY" }
   ]
  },
  {
   "title": "Cluster Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "txn/s" }
   ],
   "targets": [
    { "expr": "voltdb_cluster_txns", "legendFormat": "TRANSACTIONS" }
   ]
  }
 ]
}